### ISSUE TITLE
很好用，就是发现两个小问题

### ISSUE THREAD

**Issue by 2-3-5-7** [fangxx3863/biliNovel2Epub#1]
第一个是在 Android 上的 ReadEra 上，添加的 CSS （<style>p{text-indent:2em; padding:0px; margin:0px;}</style>）直接显示成了小说的文本。也可能是阅读器的问题，Windows 上用 Calibre 就没问题。

第二个是在 Windows 上用 Calibre 或 SumatraPDF 打开不分卷生成的 epub 文件，第一级（也就是第几卷）目录识别不出来。用 Calibre 编辑 epub 文件的目录，提示是第一级目录指向的位置不存在。也可能是阅读器的问题，用 ReadEra 就没问题。

我用不分卷、加图片的选项，转换的小说是这个 https://w.linovelib.com/novel/2428/catalog

总之这两个问题，在有的阅读器上是没问题的，所以我也不是很确定。总之还是很方便了，点赞！

目前我用 Calibre 手动编辑 epub，将一级目录指向正确的位置，然后又用替换删掉了添加的 CSS。

**Comment by wdpm** [comment]
> 第一个是在 Android 上的 ReadEra 上，添加的 CSS （<style>p{text-indent:2em; padding:0px; margin:0px;}</style>）直接显示成了小说的文本。也可能是阅读器的问题，Windows 上用 Calibre 就没问题。

这个【CSS规则不能被识别】是阅读器的问题。下面是在sigil 1.9.10中调试的结果截图：
![Snipaste_2022-08-24_14-38-03](https://user-images.githubusercontent.com/14016242/186348170-f9a4fe9e-0d5a-4fbe-9060-93a856037f3b.png)
此外，在calibre 5.43 64bit 以及 sumatraPDF v3.5.15237 pre-release 中测试显示，均正常应用CSS规则。

---

> 第二个是在 Windows 上用 Calibre 或 SumatraPDF 打开不分卷生成的 epub 文件，第一级（也就是第几卷）目录识别不出来。用 Calibre 编辑 epub 文件的目录，提示是第一级目录指向的位置不存在。也可能是阅读器的问题，用 ReadEra 就没问题。

这个问题推测是你sumatraPDF软件版本的问题。
 在 sumatraPDF v3.5.15237 pre-release 中测试卷链接跳转正常。你可以下载最新的测试版本的sumatraPDF来修复该问题。
![Snipaste_2022-08-24_14-50-58](https://user-images.githubusercontent.com/14016242/186350485-2a7cfe9b-6849-4cfd-a176-3fd43fbbd281.png)

---
此外，你可以关注本人这个项目，可以认为是当前这个项目的重写。
> https://github.com/wdpm/linovelib2epub
原因是我在阅读完这个项目的源码之后打消了发Pull Request来提升代码质量的念头，这个项目存在大量中文变量和重复代码。

总之，还是非常感谢原作者这个爬虫创意，极大地改善了阅读日本轻小说的本地体验。

**Comment by 2-3-5-7** [comment]
嗯，明白，但是不可以兼容一下更多的阅读器？
总之感谢回复~

**Comment by wdpm** [comment]
> 嗯，明白，但是不可以兼容一下更多的阅读器？

你可能把职责弄反了，如果epub制作规范，格式合法，而阅读器显示错误，那就是阅读器的问题。应该由阅读器那边进行BUG修复。例如，sumatraPDF那边我给他们反馈了两个关于显示epub的bug。

@2-3-5-7

**Comment by 2-3-5-7** [comment]
好的

**Comment by fangxx3863** [comment]
其实当时我都没有考虑那么多，纯粹是把css加到html末尾省事（  
代码重复主要是试了能用，然后就懒得去搞了  
中文变量是因为这个玩意我就是拿来试水一下中文变量，试过后发现，变量命名比英语更加困难了（  
然后就是感谢大佬能够关注到我的破项目
