### ISSUE TITLE
正文丢失,章节错乱

### ISSUE THREAD

**Issue by vhjujkgjfg** [fangxx3863/biliNovel2Epub#10]
现象
下载2958后,第一卷,第一章内容,从第一段到最后一段为止,和网页对不上

检查发现,貌似,丢失了介绍和插图,导致第一章内容,出现在 插图 书签下,
第二章内容跑第一章了.
并且之后每次有插图的页,会出现正文丢失,或者同一段重复出现n次,的情况(不知道是否是插图影响)

我下了两篇小说,都是这样,应该是都有的情况
文章中有多处zatione();

(adsbygoogle = window.adsbygoogle || []).push({});
像是放图片的函数?

**Comment by vhjujkgjfg** [comment]
看到#9的issue,再看到google,函数应该是google广告的影响...
感觉我描述的有问题,反正您下载任意长度大于一章的,然后对比,实际网页的第二章头尾段,还有下载到本地的第二章的头尾,应该是对不上的

**Comment by fangxx3863** [comment]
感谢这位大佬的贡献，Bug已修复
https://github.com/fangxx3863/biliNovel2Epub/pull/12
