### ISSUE TITLE
感谢，与一些疑问

### ISSUE THREAD

**Issue by rainbowsea123** [fangxx3863/biliNovel2Epub#3]
您好，感谢贡献代码。但是在运行过程中，从临时文件中生成epub的过程用了很长时间，请问这是否和文本字数或者选择包含图片有关呢？

**Comment by rainbowsea123** [comment]
在文件爬取完成后，我在分卷生成的循环中加了print函数来显示epub的生成进度，但是等了大概30分钟，还是停留在第一卷的生成中

**Comment by rainbowsea123** [comment]
测试了一下，如果选择不输出图片的话速度会快很多。供各位朋友参考

**Comment by fangxx3863** [comment]
这个问题看上去不好复现
或许可以试试这个大佬的重写？
https://github.com/wdpm/linovelib2epub

**Comment by rainbowsea123** [comment]
好的，谢谢！
