### ISSUE TITLE
下载内容乱码

### ISSUE THREAD

**Issue by vhjujkgjfg** [fangxx3863/biliNovel2Epub#8]
例如,下载 2958 的时候,小说正文会出现乱码

**Comment by fangxx3863** [comment]
已发现问题，在尝试修复

**Comment by fangxx3863** [comment]
因为哔轻做了混淆，直接拿html就是乱码
在浏览器端哔轻使用了一个js文件将乱码文字偏移回正常文字
目前源码已经修复，人不在家拿手机修的，过几天再上传二进制打包文件，急用可以先拉取更新源码使用
(这次一搞，这个小工具还得集成一个Chrome浏览器，下载时间也多了很多)

**Comment by wdpm** [comment]
@fangxx3863 这日子越来越难混了，以前还能直接API获取，现在图片防盗链/懒加载，文本混淆，大概率只能无头浏览器来做了。

后面怎么限制我都帮他们想好了：
- 限制IP/限制账号访问频率，使用风控系统暂时风控爬虫用户
- 各位奇奇怪怪的验证码（captcha）

最后还是回到了网络攻防的老套路，唉~

**Comment by fangxx3863** [comment]
> @fangxx3863 这日子越来越难混了，以前还能直接API获取，现在图片防盗链/懒加载，文本混淆，大概率只能无头浏览器来做了。
> 
> 后面怎么限制我都帮他们想好了：
> 
> * 限制IP/限制账号访问频率，使用风控系统暂时风控爬虫用户
> * 各位奇奇怪怪的验证码（captcha）
> 
> 最后还是回到了网络攻防的老套路，唉~

现在我的做法就是无头浏览器了，没找到有其他能加载js的库，我也懒得去分析那个js咋处理的。    

佬要是有空可以去看看，F12里面那个json2.js，没做混淆直接是源码。

**Comment by fangxx3863** [comment]
感谢这位大佬的贡献，Bug已修复
https://github.com/fangxx3863/biliNovel2Epub/pull/12
