### ISSUE TITLE
广告也爬下来了！

### ISSUE THREAD

**Issue by Imyukehan** [fangxx3863/biliNovel2Epub#9]
<img width="1347" alt="截屏2023-07-12 19 43 48" src="https://github.com/fangxx3863/biliNovel2Epub/assets/25715791/90855794-812f-48d7-adf4-b55e55f38c30">

另外插图页的图片都是lazyload，src="/images/photon.svg"，实际图片地址在data-src下，考虑单独处理下？

**Comment by vhjujkgjfg** [comment]
你的下载到本地的第二章的第一段和最后一段的内容,和网页的第二章的头尾段对得上吗,我发现会有对不上的情况

**Comment by fangxx3863** [comment]
感谢这位大佬的贡献，Bug已修复
https://github.com/fangxx3863/biliNovel2Epub/pull/12
